### ISSUE TITLE
TcpClientException("Connection rejected by server!") in Linux  

### ISSUE THREAD

**Issue by sujaykumarbs** [Code-Artist/CodeArtEng.Tcp#3]
Tcp client throws  TcpClientException("Connection rejected by server!") in Linux  

Class: TcpClientExtension.cs

//Issue with below code in linux and works in  Window 
IPAddress senderIPV4 = clientEndPoint.Address.IsIPv4MappedToIPv6 ? clientEndPoint.Address.MapToIPv4() : clientEndPoint.Address;

//works in linux with below code
IPAddress senderIPV4 = clientEndPoint.Address;

**Comment by Code-Artist** [comment]
Added a check if OS is Windows in TcpClientException in commit 222b78c51f742f8d4fb5e65918c88dcebc1e0ce8.
Please kindly check if that works fine in Linux.

**Comment by sujaykumarbs** [comment]
Thanks for the fast response. 
It is working with the fix.

**Comment by Code-Artist** [comment]
Fix added to Release 5.0.1
