### ISSUE TITLE
Sending large file fails

### ISSUE THREAD

**Issue by sujaykumarbs** [Code-Artist/CodeArtEng.Tcp#4]
Hi ,

We are using trying to send large file (more > 17kb) as JSON text, client getting partial data.

Please let me know your thoughts.

Regards,
Sujay

**Comment by Code-Artist** [comment]
Sujay,

It will be helpful for us to understand the issue further if you can provide some additional information like logs and code.

**Comment by Code-Artist** [comment]
Not reproducible, closed.
